// Human-friendly catalog for every selectable sound in the app.
// Each entry maps an EXACT Strudel sound name (see lib/sound-palette.ts) to a
// unique human label and a short vibe description, so sounds can be picked by
// how they SOUND rather than by their raw Strudel name. The label is mapped
// back to `name` afterwards.

export type Role =
  | "kick" | "snare" | "clap" | "hat" | "cymbal" | "tom" | "perc"
  | "bass" | "keys" | "pad" | "lead" | "pluck" | "guitar" | "strings"
  | "brass" | "wind" | "mallet" | "organ" | "choir" | "synth"
  | "texture" | "world" | "fx";

export interface SoundEntry {
  /** EXACT Strudel sound name (must match sound-palette.ts). */
  name: string;
  /** Human label, 1-3 words, Title Case, UNIQUE across the whole catalog. */
  label: string;
  /** What it actually SOUNDS like / its vibe — <= 8 words, lowercase. */
  desc: string;
  role: Role;
}

export interface BankEntry {
  name: string;   // exact bank name
  label: string;  // human, unique
  desc: string;   // <= 8 words vibe
}

export const SOUND_CATALOG: SoundEntry[] = [
  // ── Synth waveforms (PALETTE_SOUNDS) ──────────────────────────────────────
  { name: "sawtooth", label: "Saw Synth", desc: "bright buzzy sawtooth tone", role: "synth" },
  { name: "saw", label: "Saw Wave", desc: "raw buzzy sawtooth", role: "synth" },
  { name: "square", label: "Square Synth", desc: "hollow buzzy square wave", role: "synth" },
  { name: "sqr", label: "Square Wave", desc: "thin hollow square tone", role: "synth" },
  { name: "triangle", label: "Triangle Synth", desc: "soft mellow rounded tone", role: "synth" },
  { name: "tri", label: "Triangle Wave", desc: "smooth muted triangle tone", role: "synth" },
  { name: "sine", label: "Sine Synth", desc: "pure clean fundamental tone", role: "synth" },
  { name: "supersaw", label: "Supersaw", desc: "huge detuned stacked saws", role: "synth" },
  { name: "pulse", label: "Pulse Synth", desc: "nasal narrow pulse wave", role: "synth" },
  { name: "isaw", label: "Inverted Saw", desc: "reversed-phase buzzy saw", role: "synth" },

  // ── Noise (PALETTE_SOUNDS) ────────────────────────────────────────────────
  { name: "white", label: "White Noise", desc: "bright full-spectrum hiss", role: "texture" },
  { name: "pink", label: "Pink Noise", desc: "softer balanced warm hiss", role: "texture" },
  { name: "brown", label: "Brown Noise", desc: "deep rumbling low hiss", role: "texture" },
  { name: "crackle", label: "Crackle", desc: "vinyl-style random crackles", role: "texture" },

  // ── Core drum one-shots (PALETTE_SOUNDS) ──────────────────────────────────
  { name: "bd", label: "Kick", desc: "punchy electronic bass drum", role: "kick" },
  { name: "sd", label: "Snare", desc: "tight electronic snare hit", role: "snare" },
  { name: "rim", label: "Rimshot", desc: "sharp short rim click", role: "perc" },
  { name: "cp", label: "Clap", desc: "layered handclap burst", role: "clap" },
  { name: "hh", label: "Closed Hat", desc: "crisp short closed hi-hat", role: "hat" },
  { name: "oh", label: "Open Hat", desc: "ringing sizzling open hi-hat", role: "hat" },
  { name: "cr", label: "Crash", desc: "bright explosive crash cymbal", role: "cymbal" },
  { name: "rd", label: "Ride", desc: "shimmering sustained ride cymbal", role: "cymbal" },
  { name: "lt", label: "Low Tom", desc: "deep round low tom", role: "tom" },
  { name: "mt", label: "Mid Tom", desc: "warm round mid tom", role: "tom" },
  { name: "ht", label: "High Tom", desc: "tight round high tom", role: "tom" },
  { name: "sh", label: "Shaker", desc: "rhythmic dry shaker swish", role: "perc" },
  { name: "cb", label: "Cowbell", desc: "bright metallic cowbell clank", role: "perc" },
  { name: "tb", label: "Tambourine", desc: "jingling metal tambourine", role: "perc" },
  { name: "perc", label: "Percussion Hit", desc: "generic percussive accent", role: "perc" },

  // ── Named instrument samples (PALETTE_SOUNDS) ─────────────────────────────
  { name: "piano", label: "Piano", desc: "natural acoustic grand piano", role: "keys" },
  { name: "piano1", label: "Bright Piano", desc: "crisp clean acoustic piano", role: "keys" },
  { name: "fmpiano", label: "FM Piano", desc: "glassy digital electric piano", role: "keys" },
  { name: "steinway", label: "Steinway Piano", desc: "rich concert grand piano", role: "keys" },
  { name: "kawai", label: "Kawai Piano", desc: "warm acoustic grand piano", role: "keys" },
  { name: "casio", label: "Casio", desc: "cheap lo-fi toy keyboard", role: "keys" },
  { name: "clavisynth", label: "Clavi Synth", desc: "funky plucky clavinet synth", role: "keys" },
  { name: "jazz", label: "Jazz Kit", desc: "warm acoustic jazz drum sample", role: "perc" },
  { name: "metal", label: "Metal Hit", desc: "harsh clanging metallic hit", role: "perc" },
  { name: "east", label: "East", desc: "oriental plucked string sample", role: "world" },
  { name: "space", label: "Space", desc: "airy cosmic synth texture", role: "texture" },
  { name: "wind", label: "Wind", desc: "breathy ambient wind texture", role: "texture" },
  { name: "numbers", label: "Numbers", desc: "spoken counting voice samples", role: "fx" },
  { name: "fx", label: "Sound FX", desc: "assorted electronic sound effects", role: "fx" },
  { name: "misc", label: "Miscellaneous", desc: "grab-bag of odd samples", role: "fx" },
  { name: "insect", label: "Insect", desc: "chirping buzzing insect texture", role: "texture" },
  { name: "crow", label: "Crow", desc: "harsh cawing crow sample", role: "fx" },
  { name: "siren", label: "Siren", desc: "rising wailing alarm siren", role: "fx" },

  // ── Hand percussion & world drums (PALETTE_SOUNDS) ────────────────────────
  { name: "bongo", label: "Bongo", desc: "tight high hand drum", role: "perc" },
  { name: "conga", label: "Conga", desc: "deep open hand drum", role: "perc" },
  { name: "cajon", label: "Cajon", desc: "boxy wooden bass-snare drum", role: "perc" },
  { name: "darbuka", label: "Darbuka", desc: "sharp middle-eastern goblet drum", role: "perc" },
  { name: "framedrum", label: "Frame Drum", desc: "round resonant hand frame drum", role: "perc" },
  { name: "slitdrum", label: "Slit Drum", desc: "hollow wooden log drum", role: "perc" },
  { name: "oceandrum", label: "Ocean Drum", desc: "rolling wash of beads", role: "texture" },
  { name: "timpani", label: "Timpani", desc: "deep tuned orchestral kettledrum", role: "perc" },
  { name: "timpani2", label: "Timpani Soft", desc: "soft tuned orchestral kettledrum", role: "perc" },
  { name: "timpani_roll", label: "Timpani Roll", desc: "rumbling sustained kettledrum roll", role: "perc" },

  // ── Hand/shaker/metal percussion (PALETTE_SOUNDS) ─────────────────────────
  { name: "cabasa", label: "Cabasa", desc: "scratchy metal-bead shaker", role: "perc" },
  { name: "shaker_small", label: "Small Shaker", desc: "light quick shaker swish", role: "perc" },
  { name: "shaker_large", label: "Large Shaker", desc: "fuller heavier shaker swish", role: "perc" },
  { name: "tambourine", label: "Tambourine Hit", desc: "jingling shaken tambourine", role: "perc" },
  { name: "tambourine2", label: "Tambourine Alt", desc: "brighter jingling tambourine", role: "perc" },
  { name: "agogo", label: "Agogo", desc: "bright pitched metal bells", role: "perc" },
  { name: "cowbell", label: "Cowbell Hit", desc: "clanging metallic cowbell", role: "perc" },
  { name: "clave", label: "Clave", desc: "sharp wooden click", role: "perc" },
  { name: "woodblock", label: "Woodblock", desc: "hollow dry wood knock", role: "perc" },
  { name: "guiro", label: "Guiro", desc: "ratchety scraped gourd", role: "perc" },
  { name: "ratchet", label: "Ratchet", desc: "clattering mechanical ratchet", role: "perc" },
  { name: "vibraslap", label: "Vibraslap", desc: "buzzing rattling wooden slap", role: "perc" },
  { name: "flexatone", label: "Flexatone", desc: "wobbly warbling metal sheet", role: "perc" },
  { name: "slapstick", label: "Slapstick", desc: "sharp wooden whip-crack", role: "perc" },
  { name: "anvil", label: "Anvil", desc: "ringing struck metal anvil", role: "perc" },
  { name: "brakedrum", label: "Brake Drum", desc: "clanky struck metal drum", role: "perc" },

  // ── Bells, chimes, glass (PALETTE_SOUNDS) ─────────────────────────────────
  { name: "belltree", label: "Bell Tree", desc: "cascading shimmering small bells", role: "perc" },
  { name: "handbells", label: "Handbells", desc: "ringing tuned hand bells", role: "mallet" },
  { name: "handchimes", label: "Handchimes", desc: "soft ringing tuned chimes", role: "mallet" },
  { name: "fingercymbal", label: "Finger Cymbal", desc: "tiny bright ringing cymbal", role: "perc" },
  { name: "sleighbells", label: "Sleigh Bells", desc: "jingling festive bells", role: "perc" },
  { name: "marktrees", label: "Mark Tree", desc: "tinkling cascading chime bars", role: "perc" },
  { name: "triangles", label: "Triangle Hit", desc: "bright ringing metal triangle", role: "perc" },
  { name: "wineglass", label: "Wineglass", desc: "pure ringing crystal glass", role: "mallet" },
  { name: "wineglass_slow", label: "Wineglass Slow", desc: "slow bowed crystal glass", role: "mallet" },
  { name: "tubularbells", label: "Tubular Bells", desc: "deep ringing orchestral chimes", role: "mallet" },
  { name: "tubularbells2", label: "Tubular Bells Alt", desc: "brighter ringing orchestral chimes", role: "mallet" },

  // ── Tuned mallets (PALETTE_SOUNDS) ────────────────────────────────────────
  { name: "marimba", label: "Marimba", desc: "warm wooden mallet tone", role: "mallet" },
  { name: "balafon", label: "Balafon", desc: "buzzy african wooden xylophone", role: "mallet" },
  { name: "balafon_hard", label: "Balafon Hard", desc: "bright hard-struck wooden xylophone", role: "mallet" },
  { name: "balafon_soft", label: "Balafon Soft", desc: "mellow soft-struck wooden xylophone", role: "mallet" },
  { name: "glockenspiel", label: "Glockenspiel", desc: "bright bell-like metal mallet", role: "mallet" },
  { name: "vibraphone", label: "Vibraphone", desc: "mellow metallic shimmering mallet", role: "mallet" },
  { name: "vibraphone_soft", label: "Vibraphone Soft", desc: "soft warm shimmering mallet", role: "mallet" },
  { name: "vibraphone_bowed", label: "Vibraphone Bowed", desc: "eerie sustained bowed metal", role: "mallet" },
  { name: "xylophone_hard_ff", label: "Xylophone Hard", desc: "bright sharp loud wooden mallet", role: "mallet" },
  { name: "xylophone_hard_pp", label: "Xylophone Hard Soft", desc: "bright quiet wooden mallet", role: "mallet" },
  { name: "xylophone_medium_ff", label: "Xylophone Medium", desc: "balanced loud wooden mallet", role: "mallet" },
  { name: "xylophone_medium_pp", label: "Xylophone Medium Soft", desc: "balanced quiet wooden mallet", role: "mallet" },
  { name: "xylophone_soft_ff", label: "Xylophone Soft Loud", desc: "mellow loud wooden mallet", role: "mallet" },
  { name: "xylophone_soft_pp", label: "Xylophone Soft", desc: "mellow quiet wooden mallet", role: "mallet" },
  { name: "kalimba", label: "Kalimba", desc: "plucky metallic thumb piano", role: "mallet" },
  { name: "kalimba2", label: "Kalimba 2", desc: "warm metallic thumb piano", role: "mallet" },
  { name: "kalimba3", label: "Kalimba 3", desc: "bright metallic thumb piano", role: "mallet" },
  { name: "kalimba4", label: "Kalimba 4", desc: "mellow metallic thumb piano", role: "mallet" },
  { name: "kalimba5", label: "Kalimba 5", desc: "soft metallic thumb piano", role: "mallet" },

  // ── Plucked & bowed strings (PALETTE_SOUNDS) ──────────────────────────────
  { name: "harp", label: "Harp", desc: "lush glissando plucked strings", role: "strings" },
  { name: "folkharp", label: "Folk Harp", desc: "delicate plucked folk harp", role: "strings" },
  { name: "psaltery_pluck", label: "Psaltery Pluck", desc: "bright plucked zither strings", role: "strings" },
  { name: "psaltery_bow", label: "Psaltery Bow", desc: "sustained bowed zither strings", role: "strings" },
  { name: "psaltery_spiccato", label: "Psaltery Spiccato", desc: "short bouncy bowed zither", role: "strings" },
  { name: "strumstick", label: "Strumstick", desc: "twangy strummed folk strings", role: "guitar" },
  { name: "dantranh", label: "Dan Tranh", desc: "bright vietnamese zither pluck", role: "world" },
  { name: "dantranh_tremolo", label: "Dan Tranh Tremolo", desc: "fluttering vietnamese zither tremolo", role: "world" },
  { name: "dantranh_vibrato", label: "Dan Tranh Vibrato", desc: "wavering vietnamese zither vibrato", role: "world" },

  // ── Winds (PALETTE_SOUNDS) ────────────────────────────────────────────────
  { name: "ocarina", label: "Ocarina", desc: "round breathy clay flute", role: "wind" },
  { name: "ocarina_small", label: "Ocarina Small", desc: "high breathy clay flute", role: "wind" },
  { name: "ocarina_small_stacc", label: "Ocarina Staccato", desc: "short high breathy flute", role: "wind" },
  { name: "ocarina_vib", label: "Ocarina Vibrato", desc: "wavering breathy clay flute", role: "wind" },
  { name: "recorder_soprano_sus", label: "Soprano Recorder", desc: "high airy sustained recorder", role: "wind" },
  { name: "recorder_soprano_stacc", label: "Soprano Recorder Short", desc: "high airy short recorder", role: "wind" },
  { name: "recorder_alto_sus", label: "Alto Recorder", desc: "mid airy sustained recorder", role: "wind" },
  { name: "recorder_alto_stacc", label: "Alto Recorder Short", desc: "mid airy short recorder", role: "wind" },
  { name: "recorder_alto_vib", label: "Alto Recorder Vibrato", desc: "mid wavering airy recorder", role: "wind" },
  { name: "recorder_tenor_sus", label: "Tenor Recorder", desc: "low airy sustained recorder", role: "wind" },
  { name: "recorder_tenor_stacc", label: "Tenor Recorder Short", desc: "low airy short recorder", role: "wind" },
  { name: "recorder_tenor_vib", label: "Tenor Recorder Vibrato", desc: "low wavering airy recorder", role: "wind" },
  { name: "recorder_bass_sus", label: "Bass Recorder", desc: "deep airy sustained recorder", role: "wind" },
  { name: "recorder_bass_stacc", label: "Bass Recorder Short", desc: "deep airy short recorder", role: "wind" },
  { name: "recorder_bass_vib", label: "Bass Recorder Vibrato", desc: "deep wavering airy recorder", role: "wind" },
  { name: "harmonica", label: "Harmonica", desc: "reedy bluesy mouth organ", role: "wind" },
  { name: "harmonica_soft", label: "Harmonica Soft", desc: "mellow reedy mouth organ", role: "wind" },
  { name: "harmonica_vib", label: "Harmonica Vibrato", desc: "wavering reedy mouth organ", role: "wind" },
  { name: "super64", label: "Chromatic Harmonica", desc: "smooth jazzy chromatic harmonica", role: "wind" },
  { name: "super64_acc", label: "Chromatic Harmonica Accent", desc: "punchy accented chromatic harmonica", role: "wind" },
  { name: "super64_vib", label: "Chromatic Harmonica Vibrato", desc: "wavering chromatic harmonica", role: "wind" },
  { name: "sax", label: "Saxophone", desc: "warm reedy jazz saxophone", role: "wind" },
  { name: "sax_stacc", label: "Saxophone Short", desc: "punchy short jazz saxophone", role: "wind" },
  { name: "sax_vib", label: "Saxophone Vibrato", desc: "wavering warm jazz saxophone", role: "wind" },
  { name: "saxello", label: "Saxello", desc: "bright curved soprano sax", role: "wind" },
  { name: "saxello_stacc", label: "Saxello Short", desc: "punchy bright soprano sax", role: "wind" },
  { name: "saxello_vib", label: "Saxello Vibrato", desc: "wavering bright soprano sax", role: "wind" },
  { name: "didgeridoo", label: "Didgeridoo", desc: "droning buzzing aboriginal pipe", role: "world" },
  { name: "ballwhistle", label: "Ball Whistle", desc: "warbling slide ball whistle", role: "fx" },
  { name: "trainwhistle", label: "Train Whistle", desc: "breathy chord steam whistle", role: "fx" },

  // ── Misc atmosphere & toys (PALETTE_SOUNDS) ───────────────────────────────
  { name: "gong", label: "Gong", desc: "deep crashing shimmering gong", role: "perc" },
  { name: "gong2", label: "Gong Alt", desc: "brighter crashing shimmering gong", role: "perc" },
  { name: "clash", label: "Clash Cymbal", desc: "crashing orchestral hand cymbals", role: "cymbal" },
  { name: "clash2", label: "Clash Cymbal Alt", desc: "brighter orchestral hand cymbals", role: "cymbal" },
  { name: "sus_cymbal", label: "Suspended Cymbal", desc: "swelling sustained crash cymbal", role: "cymbal" },
  { name: "sus_cymbal2", label: "Suspended Cymbal Alt", desc: "brighter sustained crash cymbal", role: "cymbal" },

  // ── Standalone drum hits (PALETTE_SOUNDS) ─────────────────────────────────
  { name: "bassdrum1", label: "Bass Drum 1", desc: "deep acoustic bass drum", role: "kick" },
  { name: "bassdrum2", label: "Bass Drum 2", desc: "punchy acoustic bass drum", role: "kick" },
  { name: "snare_hi", label: "Snare High", desc: "tight bright acoustic snare", role: "snare" },
  { name: "snare_low", label: "Snare Low", desc: "fat deep acoustic snare", role: "snare" },
  { name: "snare_modern", label: "Snare Modern", desc: "crisp produced modern snare", role: "snare" },
  { name: "snare_rim", label: "Snare Rim", desc: "sharp snare rimshot click", role: "perc" },
  { name: "hihat", label: "Hi-Hat", desc: "crisp acoustic closed hi-hat", role: "hat" },
  { name: "clap", label: "Handclap", desc: "single dry handclap", role: "clap" },
  { name: "tom_mallet", label: "Tom Mallet", desc: "soft mallet-struck tom", role: "tom" },
  { name: "tom_rim", label: "Tom Rim", desc: "sharp tom rim hit", role: "tom" },
  { name: "tom_stick", label: "Tom Stick", desc: "punchy stick-struck tom", role: "tom" },
  { name: "tom2_mallet", label: "Tom Mallet 2", desc: "soft mallet-struck low tom", role: "tom" },
  { name: "tom2_rim", label: "Tom Rim 2", desc: "sharp low tom rim", role: "tom" },
  { name: "tom2_stick", label: "Tom Stick 2", desc: "punchy stick-struck low tom", role: "tom" },

  // ── Organ samples (PALETTE_SOUNDS) ────────────────────────────────────────
  { name: "organ_4inch", label: "Organ 4ft", desc: "bright high drawbar organ", role: "organ" },
  { name: "organ_8inch", label: "Organ 8ft", desc: "fuller mid drawbar organ", role: "organ" },
  { name: "organ_full", label: "Full Organ", desc: "rich full-stop drawbar organ", role: "organ" },
  { name: "pipeorgan_loud", label: "Pipe Organ Loud", desc: "grand booming church organ", role: "organ" },
  { name: "pipeorgan_loud_pedal", label: "Pipe Organ Loud Pedal", desc: "deep booming pedal church organ", role: "organ" },
  { name: "pipeorgan_quiet", label: "Pipe Organ Quiet", desc: "soft airy church organ", role: "organ" },
  { name: "pipeorgan_quiet_pedal", label: "Pipe Organ Quiet Pedal", desc: "soft deep pedal church organ", role: "organ" },

  // ── Mridangam & Indian percussion (PALETTE_SOUNDS) ────────────────────────
  { name: "ardha", label: "Mridangam Ardha", desc: "open indian hand-drum stroke", role: "world" },
  { name: "chaapu", label: "Mridangam Chaapu", desc: "slap indian hand-drum stroke", role: "world" },
  { name: "dhi", label: "Mridangam Dhi", desc: "resonant indian drum stroke", role: "world" },
  { name: "dhin", label: "Mridangam Dhin", desc: "ringing indian drum stroke", role: "world" },
  { name: "dhum", label: "Mridangam Dhum", desc: "deep indian bass stroke", role: "world" },
  { name: "gumki", label: "Mridangam Gumki", desc: "bending pitched indian stroke", role: "world" },
  { name: "ka", label: "Mridangam Ka", desc: "sharp indian drum tap", role: "world" },
  { name: "ki", label: "Mridangam Ki", desc: "light indian drum tap", role: "world" },
  { name: "na", label: "Mridangam Na", desc: "ringing indian rim stroke", role: "world" },
  { name: "nam", label: "Mridangam Nam", desc: "open indian rim stroke", role: "world" },
  { name: "ta", label: "Mridangam Ta", desc: "crisp indian drum stroke", role: "world" },
  { name: "tha", label: "Mridangam Tha", desc: "flat indian drum stroke", role: "world" },
  { name: "thom", label: "Mridangam Thom", desc: "deep indian bass tone", role: "world" },
  { name: "mridangam_ardha", label: "Mridangam Ardha Bank", desc: "open south-indian drum stroke", role: "world" },
  { name: "mridangam_chaapu", label: "Mridangam Chaapu Bank", desc: "slap south-indian drum stroke", role: "world" },
  { name: "mridangam_dhi", label: "Mridangam Dhi Bank", desc: "resonant south-indian stroke", role: "world" },
  { name: "mridangam_dhin", label: "Mridangam Dhin Bank", desc: "ringing south-indian stroke", role: "world" },
  { name: "mridangam_dhum", label: "Mridangam Dhum Bank", desc: "deep south-indian bass stroke", role: "world" },
  { name: "mridangam_gumki", label: "Mridangam Gumki Bank", desc: "bending pitched south-indian stroke", role: "world" },
  { name: "mridangam_ka", label: "Mridangam Ka Bank", desc: "sharp south-indian drum tap", role: "world" },
  { name: "mridangam_ki", label: "Mridangam Ki Bank", desc: "light south-indian drum tap", role: "world" },
  { name: "mridangam_na", label: "Mridangam Na Bank", desc: "ringing south-indian rim stroke", role: "world" },
  { name: "mridangam_nam", label: "Mridangam Nam Bank", desc: "open south-indian rim stroke", role: "world" },
  { name: "mridangam_ta", label: "Mridangam Ta Bank", desc: "crisp south-indian drum stroke", role: "world" },
  { name: "mridangam_tha", label: "Mridangam Tha Bank", desc: "flat south-indian drum stroke", role: "world" },
  { name: "mridangam_thom", label: "Mridangam Thom Bank", desc: "deep south-indian bass tone", role: "world" },

  // ── GM: Pianos & keys (GM_SOUNDS) ─────────────────────────────────────────
  { name: "gm_piano", label: "Grand Piano", desc: "full acoustic grand piano", role: "keys" },
  { name: "gm_epiano1", label: "Electric Piano 1", desc: "warm rhodes electric piano", role: "keys" },
  { name: "gm_epiano2", label: "Electric Piano 2", desc: "bright fm electric piano", role: "keys" },
  { name: "gm_harpsichord", label: "Harpsichord", desc: "bright plucky baroque keyboard", role: "keys" },
  { name: "gm_clavinet", label: "Clavinet", desc: "funky percussive plucked keyboard", role: "keys" },
  { name: "gm_celesta", label: "Celesta", desc: "delicate bell-like keyboard", role: "mallet" },
  { name: "gm_music_box", label: "Music Box", desc: "tinkly nostalgic music box", role: "mallet" },

  // ── GM: Organs (GM_SOUNDS) ────────────────────────────────────────────────
  { name: "gm_drawbar_organ", label: "Drawbar Organ", desc: "smooth jazzy hammond organ", role: "organ" },
  { name: "gm_percussive_organ", label: "Percussive Organ", desc: "punchy attack hammond organ", role: "organ" },
  { name: "gm_rock_organ", label: "Rock Organ", desc: "gritty overdriven rock organ", role: "organ" },
  { name: "gm_church_organ", label: "Church Organ", desc: "grand majestic pipe organ", role: "organ" },
  { name: "gm_reed_organ", label: "Reed Organ", desc: "wheezy harmonium reed organ", role: "organ" },
  { name: "gm_accordion", label: "Accordion", desc: "reedy bellows-driven accordion", role: "organ" },
  { name: "gm_harmonica", label: "GM Harmonica", desc: "reedy bluesy mouth organ", role: "wind" },
  { name: "gm_bandoneon", label: "Bandoneon", desc: "expressive tango bellows reed", role: "organ" },

  // ── GM: Guitars (GM_SOUNDS) ───────────────────────────────────────────────
  { name: "gm_acoustic_guitar_nylon", label: "Nylon Guitar", desc: "soft warm classical guitar", role: "guitar" },
  { name: "gm_acoustic_guitar_steel", label: "Steel Guitar", desc: "bright ringing acoustic guitar", role: "guitar" },
  { name: "gm_electric_guitar_jazz", label: "Jazz Guitar", desc: "warm mellow hollow-body guitar", role: "guitar" },
  { name: "gm_electric_guitar_clean", label: "Clean Guitar", desc: "bright clean electric guitar", role: "guitar" },
  { name: "gm_electric_guitar_muted", label: "Muted Guitar", desc: "tight palm-muted electric guitar", role: "guitar" },
  { name: "gm_overdriven_guitar", label: "Overdriven Guitar", desc: "crunchy overdriven electric guitar", role: "guitar" },
  { name: "gm_distortion_guitar", label: "Distortion Guitar", desc: "heavy distorted electric guitar", role: "guitar" },
  { name: "gm_guitar_harmonics", label: "Guitar Harmonics", desc: "chiming bell-like guitar harmonics", role: "guitar" },
  { name: "gm_guitar_fret_noise", label: "Fret Noise", desc: "squeaky string-slide guitar noise", role: "fx" },

  // ── GM: Basses (GM_SOUNDS) ────────────────────────────────────────────────
  { name: "gm_acoustic_bass", label: "Acoustic Bass", desc: "warm upright jazz double bass", role: "bass" },
  { name: "gm_electric_bass_finger", label: "Finger Bass", desc: "round fingered electric bass", role: "bass" },
  { name: "gm_electric_bass_pick", label: "Pick Bass", desc: "bright picked electric bass", role: "bass" },
  { name: "gm_fretless_bass", label: "Fretless Bass", desc: "smooth singing fretless bass", role: "bass" },
  { name: "gm_slap_bass_1", label: "Slap Bass 1", desc: "funky snappy slap bass", role: "bass" },
  { name: "gm_slap_bass_2", label: "Slap Bass 2", desc: "punchy popping slap bass", role: "bass" },
  { name: "gm_synth_bass_1", label: "Synth Bass 1", desc: "round analog synth bass", role: "bass" },
  { name: "gm_synth_bass_2", label: "Synth Bass 2", desc: "buzzy aggressive synth bass", role: "bass" },

  // ── GM: Strings & orchestral (GM_SOUNDS) ──────────────────────────────────
  { name: "gm_violin", label: "Violin", desc: "expressive bowed solo violin", role: "strings" },
  { name: "gm_viola", label: "Viola", desc: "warm bowed solo viola", role: "strings" },
  { name: "gm_cello", label: "Cello", desc: "rich bowed solo cello", role: "strings" },
  { name: "gm_contrabass", label: "Contrabass", desc: "deep bowed double bass", role: "strings" },
  { name: "gm_tremolo_strings", label: "Tremolo Strings", desc: "shimmering trembling string section", role: "strings" },
  { name: "gm_pizzicato_strings", label: "Pizzicato Strings", desc: "plucked staccato string section", role: "strings" },
  { name: "gm_orchestral_harp", label: "Orchestral Harp", desc: "lush sweeping concert harp", role: "strings" },
  { name: "gm_string_ensemble_1", label: "String Ensemble 1", desc: "lush full bowed strings", role: "strings" },
  { name: "gm_string_ensemble_2", label: "String Ensemble 2", desc: "warm slow bowed strings", role: "strings" },
  { name: "gm_synth_strings_1", label: "Synth Strings 1", desc: "smooth synthetic string pad", role: "strings" },
  { name: "gm_synth_strings_2", label: "Synth Strings 2", desc: "airy synthetic string pad", role: "strings" },
  { name: "gm_timpani", label: "GM Timpani", desc: "deep tuned orchestral kettledrum", role: "perc" },
  { name: "gm_orchestra_hit", label: "Orchestra Hit", desc: "punchy stabbing orchestral chord", role: "fx" },

  // ── GM: Brass (GM_SOUNDS) ─────────────────────────────────────────────────
  { name: "gm_trumpet", label: "Trumpet", desc: "bright brassy solo trumpet", role: "brass" },
  { name: "gm_trombone", label: "Trombone", desc: "warm sliding solo trombone", role: "brass" },
  { name: "gm_tuba", label: "Tuba", desc: "deep round low brass", role: "brass" },
  { name: "gm_muted_trumpet", label: "Muted Trumpet", desc: "nasal muted solo trumpet", role: "brass" },
  { name: "gm_french_horn", label: "French Horn", desc: "warm round mellow horn", role: "brass" },
  { name: "gm_brass_section", label: "Brass Section", desc: "punchy full brass ensemble", role: "brass" },
  { name: "gm_synth_brass_1", label: "Synth Brass 1", desc: "fat punchy synth brass", role: "brass" },
  { name: "gm_synth_brass_2", label: "Synth Brass 2", desc: "bright analog synth brass", role: "brass" },

  // ── GM: Reeds (GM_SOUNDS) ─────────────────────────────────────────────────
  { name: "gm_soprano_sax", label: "Soprano Sax", desc: "bright reedy high saxophone", role: "wind" },
  { name: "gm_alto_sax", label: "Alto Sax", desc: "warm reedy alto saxophone", role: "wind" },
  { name: "gm_tenor_sax", label: "Tenor Sax", desc: "rich reedy tenor saxophone", role: "wind" },
  { name: "gm_baritone_sax", label: "Baritone Sax", desc: "deep reedy low saxophone", role: "wind" },
  { name: "gm_oboe", label: "Oboe", desc: "nasal reedy double-reed wind", role: "wind" },
  { name: "gm_english_horn", label: "English Horn", desc: "warm mellow double-reed wind", role: "wind" },
  { name: "gm_bassoon", label: "Bassoon", desc: "deep woody double-reed wind", role: "wind" },
  { name: "gm_clarinet", label: "Clarinet", desc: "smooth hollow woodwind reed", role: "wind" },

  // ── GM: Pipes (GM_SOUNDS) ─────────────────────────────────────────────────
  { name: "gm_piccolo", label: "Piccolo", desc: "shrill bright high flute", role: "wind" },
  { name: "gm_flute", label: "Flute", desc: "airy clear classical flute", role: "wind" },
  { name: "gm_recorder", label: "Recorder", desc: "soft breathy wooden flute", role: "wind" },
  { name: "gm_pan_flute", label: "Pan Flute", desc: "breathy hollow andean flute", role: "wind" },
  { name: "gm_blown_bottle", label: "Blown Bottle", desc: "hollow breathy bottle tone", role: "wind" },
  { name: "gm_shakuhachi", label: "Shakuhachi", desc: "breathy haunting japanese flute", role: "wind" },
  { name: "gm_whistle", label: "Whistle", desc: "pure clear human whistle", role: "wind" },
  { name: "gm_ocarina", label: "GM Ocarina", desc: "round breathy clay flute", role: "wind" },

  // ── GM: Synth leads (GM_SOUNDS) ───────────────────────────────────────────
  { name: "gm_lead_1_square", label: "Square Lead", desc: "hollow retro square lead", role: "lead" },
  { name: "gm_lead_2_sawtooth", label: "Saw Lead", desc: "buzzy bright sawtooth lead", role: "lead" },
  { name: "gm_lead_3_calliope", label: "Calliope Lead", desc: "breathy round flute-like lead", role: "lead" },
  { name: "gm_lead_4_chiff", label: "Chiff Lead", desc: "breathy chiffy attack lead", role: "lead" },
  { name: "gm_lead_5_charang", label: "Charang Lead", desc: "gritty buzzy guitar-like lead", role: "lead" },
  { name: "gm_lead_6_voice", label: "Voice Lead", desc: "vocal-like synth lead", role: "lead" },
  { name: "gm_lead_7_fifths", label: "Fifths Lead", desc: "stacked-fifths fat synth lead", role: "lead" },
  { name: "gm_lead_8_bass_lead", label: "Bass Lead", desc: "thick low synth lead", role: "lead" },

  // ── GM: Synth pads (GM_SOUNDS) ────────────────────────────────────────────
  { name: "gm_pad_new_age", label: "New Age Pad", desc: "shimmering bright airy pad", role: "pad" },
  { name: "gm_pad_warm", label: "Warm Pad", desc: "warm soft analog pad", role: "pad" },
  { name: "gm_pad_poly", label: "Poly Pad", desc: "bright polysynth chord pad", role: "pad" },
  { name: "gm_pad_choir", label: "Choir Pad", desc: "breathy vocal-like synth pad", role: "pad" },
  { name: "gm_pad_bowed", label: "Bowed Pad", desc: "swelling bowed-glass synth pad", role: "pad" },
  { name: "gm_pad_metallic", label: "Metallic Pad", desc: "cold metallic shimmering pad", role: "pad" },
  { name: "gm_pad_halo", label: "Halo Pad", desc: "ethereal glowing choral pad", role: "pad" },
  { name: "gm_pad_sweep", label: "Sweep Pad", desc: "filter-sweeping evolving pad", role: "pad" },

  // ── GM: Synth FX (GM_SOUNDS) ──────────────────────────────────────────────
  { name: "gm_fx_rain", label: "Rain FX", desc: "tinkling falling-droplet texture", role: "fx" },
  { name: "gm_fx_soundtrack", label: "Soundtrack FX", desc: "cinematic sweeping ambient texture", role: "fx" },
  { name: "gm_fx_crystal", label: "Crystal FX", desc: "glassy sparkling bell texture", role: "fx" },
  { name: "gm_fx_atmosphere", label: "Atmosphere FX", desc: "warm dreamy ambient texture", role: "fx" },
  { name: "gm_fx_brightness", label: "Brightness FX", desc: "bright shimmering airy texture", role: "fx" },
  { name: "gm_fx_goblins", label: "Goblins FX", desc: "eerie whispering voice texture", role: "fx" },
  { name: "gm_fx_echoes", label: "Echoes FX", desc: "drifting echoing bell texture", role: "fx" },
  { name: "gm_fx_sci_fi", label: "Sci-Fi FX", desc: "futuristic spacey synth texture", role: "fx" },

  // ── GM: Ethnic (GM_SOUNDS) ────────────────────────────────────────────────
  { name: "gm_sitar", label: "Sitar", desc: "buzzy droning indian strings", role: "world" },
  { name: "gm_banjo", label: "Banjo", desc: "bright twangy plucked banjo", role: "guitar" },
  { name: "gm_shamisen", label: "Shamisen", desc: "twangy japanese plucked strings", role: "world" },
  { name: "gm_koto", label: "Koto", desc: "plucked japanese zither strings", role: "world" },
  { name: "gm_kalimba", label: "GM Kalimba", desc: "plucky metallic thumb piano", role: "mallet" },
  { name: "gm_bagpipe", label: "Bagpipe", desc: "droning reedy scottish pipes", role: "world" },
  { name: "gm_fiddle", label: "Fiddle", desc: "lively bowed folk violin", role: "strings" },
  { name: "gm_shanai", label: "Shanai", desc: "nasal reedy indian oboe", role: "world" },
  { name: "gm_dulcimer", label: "Dulcimer", desc: "shimmering hammered string instrument", role: "world" },

  // ── GM: Percussive (GM_SOUNDS) ────────────────────────────────────────────
  { name: "gm_tinkle_bell", label: "Tinkle Bell", desc: "tiny bright tinkling bell", role: "mallet" },
  { name: "gm_agogo", label: "GM Agogo", desc: "bright pitched metal bells", role: "perc" },
  { name: "gm_steel_drums", label: "Steel Drums", desc: "bright caribbean steel pan", role: "mallet" },
  { name: "gm_woodblock", label: "GM Woodblock", desc: "hollow dry wood knock", role: "perc" },
  { name: "gm_taiko_drum", label: "Taiko Drum", desc: "deep booming japanese drum", role: "perc" },
  { name: "gm_melodic_tom", label: "Melodic Tom", desc: "tuned pitched tom hit", role: "tom" },
  { name: "gm_synth_drum", label: "Synth Drum", desc: "electronic pitched tom hit", role: "tom" },
  { name: "gm_reverse_cymbal", label: "Reverse Cymbal", desc: "swelling backwards cymbal swell", role: "cymbal" },

  // ── GM: Tuned mallets & bells (GM_SOUNDS) ─────────────────────────────────
  { name: "gm_glockenspiel", label: "GM Glockenspiel", desc: "bright bell-like metal mallet", role: "mallet" },
  { name: "gm_vibraphone", label: "GM Vibraphone", desc: "mellow metallic shimmering mallet", role: "mallet" },
  { name: "gm_marimba", label: "GM Marimba", desc: "warm wooden mallet tone", role: "mallet" },
  { name: "gm_xylophone", label: "GM Xylophone", desc: "bright sharp wooden mallet", role: "mallet" },
  { name: "gm_tubular_bells", label: "GM Tubular Bells", desc: "deep ringing orchestral chimes", role: "mallet" },

  // ── GM: Choir & voice (GM_SOUNDS) ─────────────────────────────────────────
  { name: "gm_choir_aahs", label: "Choir Aahs", desc: "lush voices singing aah", role: "choir" },
  { name: "gm_voice_oohs", label: "Voice Oohs", desc: "warm voices singing ooh", role: "choir" },
  { name: "gm_synth_choir", label: "Synth Choir", desc: "smooth synthetic vocal pad", role: "choir" },

  // ── GM: Sound effects (GM_SOUNDS) ─────────────────────────────────────────
  { name: "gm_seashore", label: "Seashore", desc: "rolling ocean waves wash", role: "texture" },
  { name: "gm_bird_tweet", label: "Bird Tweet", desc: "chirping tweeting bird sounds", role: "fx" },
  { name: "gm_telephone", label: "Telephone", desc: "ringing vintage telephone bell", role: "fx" },
  { name: "gm_helicopter", label: "Helicopter", desc: "thumping rotor-blade whir", role: "fx" },
  { name: "gm_applause", label: "Applause", desc: "crowd clapping cheering noise", role: "fx" },
  { name: "gm_gunshot", label: "Gunshot", desc: "sharp explosive gun blast", role: "fx" },
  { name: "gm_breath_noise", label: "Breath Noise", desc: "airy human breath sound", role: "fx" },

  // ── Wavetables (WT_SOUNDS) ────────────────────────────────────────────────
  { name: "wt_digital", label: "Digital Wavetable", desc: "cold digital wavetable tone", role: "synth" },
  { name: "wt_digital_bad_day", label: "Bad Day Wavetable", desc: "gritty unsettled wavetable tone", role: "synth" },
  { name: "wt_digital_basique", label: "Basique Wavetable", desc: "clean simple wavetable tone", role: "synth" },
  { name: "wt_digital_crickets", label: "Crickets Wavetable", desc: "chirpy granular wavetable texture", role: "synth" },
  { name: "wt_digital_curses", label: "Curses Wavetable", desc: "harsh dark wavetable tone", role: "synth" },
  { name: "wt_digital_echoes", label: "Echoes Wavetable", desc: "drifting echoing wavetable texture", role: "synth" },
  { name: "wt_vgame", label: "Video Game Wavetable", desc: "chippy retro game wavetable", role: "synth" },
  // -- Dirt-Samples: the FULL classic TidalCycles library (s("name"); each = a folder of variants) --
  { name: "brk", label: "Break Hit", desc: "drum break fill one-shot", role: "perc" },
  { name: "808", label: "808 Kit", desc: "classic tr-808 drum machine kit", role: "perc" },
  { name: "909", label: "909 Kit", desc: "punchy tr-909 drum machine kit", role: "perc" },
  { name: "808bd", label: "808 Kick", desc: "deep boomy 808 bass drum", role: "kick" },
  { name: "808cy", label: "808 Cymbal", desc: "metallic 808 cymbal crash", role: "cymbal" },
  { name: "808hc", label: "808 Hi Conga", desc: "high 808 conga tone", role: "perc" },
  { name: "808ht", label: "808 High Tom", desc: "high pitched 808 tom", role: "tom" },
  { name: "808lc", label: "808 Lo Conga", desc: "low 808 conga tone", role: "perc" },
  { name: "808lt", label: "808 Low Tom", desc: "deep 808 tom", role: "tom" },
  { name: "808mc", label: "808 Mid Conga", desc: "mid 808 conga tone", role: "perc" },
  { name: "808mt", label: "808 Mid Tom", desc: "mid 808 tom", role: "tom" },
  { name: "808oh", label: "808 Open Hat", desc: "sizzly open 808 hihat", role: "hat" },
  { name: "808sd", label: "808 Snare", desc: "snappy 808 snare drum", role: "snare" },
  { name: "ab", label: "Dirt AB", desc: "abstract lo-fi one-shots", role: "texture" },
  { name: "ade", label: "Ade", desc: "lo-fi sample one-shots", role: "texture" },
  { name: "ades2", label: "Ade Two", desc: "lo-fi sample one-shots", role: "texture" },
  { name: "ades3", label: "Ade Three", desc: "lo-fi sample one-shots", role: "texture" },
  { name: "ades4", label: "Ade Four", desc: "lo-fi sample one-shots", role: "texture" },
  { name: "alex", label: "Alex", desc: "sampled drum hits", role: "perc" },
  { name: "alphabet", label: "Alphabet", desc: "spoken letters of the alphabet", role: "texture" },
  { name: "amencutup", label: "Amen Cutup", desc: "chopped classic amen break", role: "perc" },
  { name: "armora", label: "Armora", desc: "retro arcade game sfx", role: "fx" },
  { name: "arp", label: "Arp", desc: "synth arpeggio sequence", role: "synth" },
  { name: "arpy", label: "Arpy", desc: "bright cheerful synth arp", role: "synth" },
  { name: "auto", label: "Auto", desc: "car and engine sound effects", role: "fx" },
  { name: "baa", label: "Baa", desc: "sheep bleat vocal sample", role: "texture" },
  { name: "baa2", label: "Baa Two", desc: "second sheep bleat sample", role: "texture" },
  { name: "bass", label: "Bass", desc: "general synth bass tones", role: "bass" },
  { name: "bass0", label: "Bass Zero", desc: "synth bass one-shot", role: "bass" },
  { name: "bass1", label: "Bass One", desc: "synth bass one-shot", role: "bass" },
  { name: "bass2", label: "Bass Two", desc: "synth bass one-shot", role: "bass" },
  { name: "bass3", label: "Bass Three", desc: "synth bass one-shot", role: "bass" },
  { name: "bassdm", label: "Bass DM", desc: "vintage 808-family kick hits", role: "kick" },
  { name: "bassfoo", label: "Bass Foo", desc: "warm synth bass tone", role: "bass" },
  { name: "battles", label: "Battles", desc: "abstract glitchy sample hits", role: "texture" },
  { name: "bend", label: "Bend", desc: "pitch-bending synth tone", role: "synth" },
  { name: "bev", label: "Bev", desc: "misc personal sample hits", role: "texture" },
  { name: "bin", label: "Bin", desc: "lo-fi sample one-shots", role: "texture" },
  { name: "birds", label: "Birds", desc: "chirping birdsong field recording", role: "texture" },
  { name: "birds3", label: "Birds Three", desc: "more chirping birdsong recording", role: "texture" },
  { name: "bleep", label: "Bleep", desc: "short electronic synth bleep", role: "synth" },
  { name: "blip", label: "Blip", desc: "tiny digital synth blip", role: "synth" },
  { name: "blue", label: "Blue", desc: "abstract lo-fi one-shots", role: "texture" },
  { name: "bottle", label: "Bottle", desc: "blown glass bottle tone", role: "perc" },
  { name: "breaks125", label: "Breaks 125", desc: "drum break loop at 125bpm", role: "perc" },
  { name: "breaks152", label: "Breaks 152", desc: "drum break loop at 152bpm", role: "perc" },
  { name: "breaks157", label: "Breaks 157", desc: "drum break loop at 157bpm", role: "perc" },
  { name: "breaks165", label: "Breaks 165", desc: "drum break loop at 165bpm", role: "perc" },
  { name: "breath", label: "Breath", desc: "human breath sample", role: "texture" },
  { name: "bubble", label: "Bubble", desc: "watery bubble pops", role: "fx" },
  { name: "can", label: "Can", desc: "metal can percussive hit", role: "perc" },
  { name: "cc", label: "CC Cymbal", desc: "crash cymbal hit", role: "cymbal" },
  { name: "chin", label: "Chin", desc: "chinese percussion hit", role: "perc" },
  { name: "circus", label: "Circus", desc: "circus organ carnival tone", role: "organ" },
  { name: "clak", label: "Clak", desc: "sharp wooden click", role: "perc" },
  { name: "click", label: "Click", desc: "tight metronome click", role: "perc" },
  { name: "clubkick", label: "Club Kick", desc: "punchy club bass drum", role: "kick" },
  { name: "co", label: "Dirt Conga", desc: "hand conga drum hit", role: "perc" },
  { name: "coins", label: "Coins", desc: "arcade coin pickup sfx", role: "fx" },
  { name: "control", label: "Control", desc: "abstract lo-fi one-shots", role: "texture" },
  { name: "cosmicg", label: "Cosmic G", desc: "retro space game tone", role: "fx" },
  { name: "d", label: "Dirt D", desc: "abstract lo-fi one-shots", role: "texture" },
  { name: "db", label: "Dirt DB", desc: "sampled drum kit hits", role: "perc" },
  { name: "diphone", label: "Diphone", desc: "robotic vocal synthesis", role: "texture" },
  { name: "diphone2", label: "Diphone Two", desc: "more robotic vocal synthesis", role: "texture" },
  { name: "dist", label: "Dist", desc: "distorted industrial drum hits", role: "perc" },
  { name: "dork2", label: "Dork Two", desc: "abstract glitch textures", role: "texture" },
  { name: "dorkbot", label: "Dorkbot", desc: "abstract glitch textures", role: "texture" },
  { name: "dr", label: "Drum Kit", desc: "general drum-machine kit", role: "perc" },
  { name: "dr2", label: "Drum Kit Two", desc: "another drum-machine kit", role: "perc" },
  { name: "dr55", label: "DR-55", desc: "boss dr-55 vintage drum kit", role: "perc" },
  { name: "dr_few", label: "Drum Few", desc: "small drum-machine kit", role: "perc" },
  { name: "drum", label: "Drum", desc: "basic drum-machine kit", role: "perc" },
  { name: "drumtraks", label: "Drumtraks", desc: "sequential drumtraks vintage kit", role: "perc" },
  { name: "e", label: "Dirt E", desc: "abstract lo-fi one-shots", role: "texture" },
  { name: "electro1", label: "Electro One", desc: "electro-style drum kit", role: "perc" },
  { name: "em2", label: "EM2", desc: "warm analog synth tone", role: "synth" },
  { name: "erk", label: "Erk", desc: "misc personal sample hits", role: "texture" },
  { name: "f", label: "Dirt F", desc: "abstract lo-fi one-shots", role: "texture" },
  { name: "feel", label: "Feel", desc: "soft mellow drum kit", role: "perc" },
  { name: "feelfx", label: "Feel FX", desc: "soft kit with effects", role: "perc" },
  { name: "fest", label: "Fest", desc: "abstract lo-fi one-shots", role: "texture" },
  { name: "fire", label: "Fire", desc: "crackling campfire ambience", role: "texture" },
  { name: "flick", label: "Flick", desc: "finger flick percussion", role: "perc" },
  { name: "fm", label: "FM Synth", desc: "metallic fm synthesis tone", role: "synth" },
  { name: "foo", label: "Foo", desc: "drum break one-shots", role: "perc" },
  { name: "future", label: "Future", desc: "beefy 808 kick one-shots", role: "kick" },
  { name: "gab", label: "Gab", desc: "distorted gabber kick", role: "kick" },
  { name: "gabba", label: "Gabba", desc: "distorted gabber kick drum", role: "kick" },
  { name: "gabbaloud", label: "Gabba Loud", desc: "louder distorted gabber kick", role: "kick" },
  { name: "gabbalouder", label: "Gabba Louder", desc: "loudest distorted gabber kick", role: "kick" },
  { name: "glasstap", label: "Glass Tap", desc: "tapped glass ping", role: "perc" },
  { name: "glitch", label: "Glitch", desc: "glitchy electronic drum kit", role: "perc" },
  { name: "glitch2", label: "Glitch Two", desc: "more glitchy electronic drums", role: "perc" },
  { name: "gretsch", label: "Gretsch Kit", desc: "acoustic gretsch drum kit", role: "perc" },
  { name: "gtr", label: "Guitar", desc: "clean electric guitar note", role: "guitar" },
  { name: "h", label: "Dirt H", desc: "abstract lo-fi one-shots", role: "texture" },
  { name: "hand", label: "Hand", desc: "hand percussion hit", role: "perc" },
  { name: "hardcore", label: "Hardcore", desc: "hardcore distorted kick", role: "kick" },
  { name: "hardkick", label: "Hard Kick", desc: "aggressive hardcore kick drum", role: "kick" },
  { name: "haw", label: "Haw", desc: "lo-fi hawaiian drum kit", role: "perc" },
  { name: "hc", label: "HC", desc: "crisp closed hi-hat hits", role: "hat" },
  { name: "hh27", label: "Hat 27", desc: "tight closed hihat", role: "hat" },
  { name: "hit", label: "Hit", desc: "punchy orchestral stab hit", role: "fx" },
  { name: "hmm", label: "Hmm", desc: "vocal hum sample", role: "texture" },
  { name: "ho", label: "Dirt Open Hat", desc: "open hihat cymbal", role: "hat" },
  { name: "hoover", label: "Hoover", desc: "classic rave hoover lead", role: "lead" },
  { name: "house", label: "House Kit", desc: "house music drum kit", role: "perc" },
  { name: "if", label: "Dirt IF", desc: "gabber kick and snarl hits", role: "perc" },
  { name: "ifdrums", label: "IF Drums", desc: "misc drum-machine hits", role: "perc" },
  { name: "incoming", label: "Incoming", desc: "incoming missile sound effect", role: "fx" },
  { name: "industrial", label: "Industrial", desc: "harsh metallic industrial kit", role: "perc" },
  { name: "invaders", label: "Invaders", desc: "space invaders arcade sfx", role: "fx" },
  { name: "jungbass", label: "Jungle Bass", desc: "deep jungle reese bass", role: "bass" },
  { name: "jungle", label: "Jungle", desc: "fast jungle drum break", role: "perc" },
  { name: "juno", label: "Juno", desc: "lush roland juno synth", role: "keys" },
  { name: "jvbass", label: "JV Bass", desc: "rubbery acid synth bass", role: "bass" },
  { name: "kicklinn", label: "Linn Kick", desc: "linndrum bass drum", role: "kick" },
  { name: "koy", label: "Koy", desc: "misc personal sample hits", role: "texture" },
  { name: "kurt", label: "Kurt", desc: "misc personal sample hits", role: "texture" },
  { name: "latibro", label: "Latibro", desc: "abstract glitch textures", role: "texture" },
  { name: "led", label: "Led", desc: "abstract lo-fi one-shots", role: "texture" },
  { name: "less", label: "Less", desc: "sparse kick snare hat hits", role: "perc" },
  { name: "lighter", label: "Lighter", desc: "lighter flick click", role: "fx" },
  { name: "linnhats", label: "Linn Hats", desc: "linndrum hihat hits", role: "hat" },
  { name: "made", label: "Made", desc: "misc personal sample hits", role: "texture" },
  { name: "made2", label: "Made Two", desc: "more misc sample hits", role: "texture" },
  { name: "mash", label: "Mash", desc: "abstract glitch textures", role: "texture" },
  { name: "mash2", label: "Mash Two", desc: "more abstract glitch textures", role: "texture" },
  { name: "miniyeah", label: "Mini Yeah", desc: "short yeah vocal shout", role: "texture" },
  { name: "monsterb", label: "Monster B", desc: "monster bash arcade sfx", role: "fx" },
  { name: "moog", label: "Moog", desc: "fat moog synth bass", role: "bass" },
  { name: "mouth", label: "Mouth", desc: "mouth beatbox vocal sounds", role: "texture" },
  { name: "mp3", label: "MP3", desc: "lo-fi compressed sample hits", role: "texture" },
  { name: "msg", label: "Msg", desc: "abstract lo-fi one-shots", role: "texture" },
  { name: "mute", label: "Mute", desc: "muted plucky synth note", role: "synth" },
  { name: "newnotes", label: "New Notes", desc: "tonal synth note hits", role: "synth" },
  { name: "noise", label: "Noise", desc: "white noise burst", role: "fx" },
  { name: "noise2", label: "Noise Two", desc: "more white noise textures", role: "fx" },
  { name: "notes", label: "Notes", desc: "tonal synth note hits", role: "synth" },
  { name: "num", label: "Num", desc: "spoken counting numbers", role: "texture" },
  { name: "oc", label: "Dirt OC", desc: "abstract lo-fi one-shots", role: "texture" },
  { name: "odx", label: "Oberheim DX", desc: "oberheim dx drum kit", role: "perc" },
  { name: "off", label: "Off", desc: "abstract lo-fi one-shots", role: "texture" },
  { name: "outdoor", label: "Outdoor", desc: "outdoor ambient field recording", role: "texture" },
  { name: "pad", label: "Pad", desc: "warm sustained synth pad", role: "pad" },
  { name: "padlong", label: "Pad Long", desc: "long evolving synth pad", role: "pad" },
  { name: "pebbles", label: "Pebbles", desc: "rattling pebble stones", role: "texture" },
  { name: "peri", label: "Peri", desc: "electronic drum kit hits", role: "perc" },
  { name: "pluck", label: "Pluck", desc: "plucked synth string", role: "pluck" },
  { name: "popkick", label: "Pop Kick", desc: "clean pop bass drum", role: "kick" },
  { name: "print", label: "Print", desc: "dot-matrix printer sounds", role: "fx" },
  { name: "proc", label: "Proc", desc: "abstract glitch textures", role: "texture" },
  { name: "procshort", label: "Proc Short", desc: "short glitch artifacts", role: "texture" },
  { name: "psr", label: "PSR", desc: "yamaha psr home keyboard", role: "keys" },
  { name: "rave", label: "Rave", desc: "energetic rave synth stab", role: "synth" },
  { name: "rave2", label: "Rave Two", desc: "more rave synth stabs", role: "synth" },
  { name: "ravemono", label: "Rave Mono", desc: "mono rave synth stab", role: "synth" },
  { name: "realclaps", label: "Real Claps", desc: "layered acoustic hand claps", role: "clap" },
  { name: "reverbkick", label: "Reverb Kick", desc: "spacious reverbed bass drum", role: "kick" },
  { name: "rm", label: "Dirt RM", desc: "sharp rimshot hits", role: "perc" },
  { name: "rs", label: "Dirt Rimshot", desc: "snappy drum rimshot", role: "perc" },
  { name: "seawolf", label: "Seawolf", desc: "submarine sonar ping sfx", role: "fx" },
  { name: "sequential", label: "Sequential", desc: "sequential analog synth tone", role: "synth" },
  { name: "sf", label: "Dirt SF", desc: "abstract lo-fi one-shots", role: "texture" },
  { name: "sheffield", label: "Sheffield", desc: "misc personal sample hits", role: "texture" },
  { name: "short", label: "Short", desc: "very short blip hit", role: "fx" },
  { name: "sid", label: "SID", desc: "c64 sid chiptune tone", role: "synth" },
  { name: "simplesine", label: "Simple Sine", desc: "pure clean sine tone", role: "synth" },
  { name: "sitar", label: "Lo-fi Sitar", desc: "plucked indian sitar string", role: "strings" },
  { name: "sn", label: "Dirt Snare", desc: "acoustic snare drum hit", role: "snare" },
  { name: "speakspell", label: "Speak Spell", desc: "speak and spell toy voice", role: "texture" },
  { name: "speech", label: "Speech", desc: "spoken word vocal sample", role: "texture" },
  { name: "speechless", label: "Speechless", desc: "wordless vocal sample", role: "texture" },
  { name: "speedupdown", label: "Speed Up Down", desc: "pitch sweeping tape effect", role: "fx" },
  { name: "stab", label: "Stab", desc: "punchy synth chord stab", role: "synth" },
  { name: "stomp", label: "Stomp", desc: "heavy foot stomp", role: "perc" },
  { name: "subroc3d", label: "Subroc 3D", desc: "subroc 3d arcade sfx", role: "fx" },
  { name: "sugar", label: "Sugar", desc: "misc personal sample hits", role: "texture" },
  { name: "sundance", label: "Sundance", desc: "abstract lo-fi one-shots", role: "texture" },
  { name: "tabla", label: "Tabla", desc: "indian tabla hand drum", role: "perc" },
  { name: "tabla2", label: "Tabla Two", desc: "more indian tabla hits", role: "perc" },
  { name: "tablex", label: "Tabla X", desc: "extended tabla drum hits", role: "perc" },
  { name: "tacscan", label: "Tac Scan", desc: "tac/scan arcade game sfx", role: "fx" },
  { name: "tech", label: "Tech", desc: "techno drum kit", role: "perc" },
  { name: "techno", label: "Techno", desc: "driving techno drum kit", role: "perc" },
  { name: "tink", label: "Tink", desc: "metallic high ping", role: "perc" },
  { name: "tok", label: "Tok", desc: "misc percussion hits", role: "perc" },
  { name: "toys", label: "Toys", desc: "playful toy sound effects", role: "fx" },
  { name: "trump", label: "Dirt Trumpet", desc: "brassy trumpet note", role: "brass" },
  { name: "ul", label: "Dirt UL", desc: "lo-fi kick and hat hits", role: "perc" },
  { name: "ulgab", label: "UL Gab", desc: "distorted gabber kick variant", role: "kick" },
  { name: "uxay", label: "Uxay", desc: "abstract glitch textures", role: "texture" },
  { name: "v", label: "Dirt V", desc: "blippy percussion and snare hits", role: "perc" },
  { name: "voodoo", label: "Voodoo", desc: "tribal voodoo drum kit", role: "perc" },
  { name: "wobble", label: "Wobble", desc: "modulating wobble bass", role: "bass" },
  { name: "world", label: "World", desc: "assorted world percussion hits", role: "world" },
  { name: "xmas", label: "Xmas", desc: "jingling sleigh bells", role: "perc" },
  { name: "yeah", label: "Yeah", desc: "yeah vocal shout sample", role: "texture" },
];

export const BANK_CATALOG: BankEntry[] = [
  { name: "AJKPercusyn", label: "AJK Percusyn", desc: "rare analog drum-synth percussion" },
  { name: "AkaiLinn", label: "Akai Linn", desc: "classic sampled linn-style kit" },
  { name: "AkaiMPC60", label: "Akai MPC60", desc: "gritty golden-era sampler drums" },
  { name: "AkaiXR10", label: "Akai XR10", desc: "punchy late-80s sampled drums" },
  { name: "AlesisHR16", label: "Alesis HR16", desc: "dry realistic 80s sampled drums" },
  { name: "AlesisSR16", label: "Alesis SR16", desc: "clean versatile 90s sampled drums" },
  { name: "BossDR110", label: "Boss DR110", desc: "thin analog drumatix kit" },
  { name: "BossDR220", label: "Boss DR220", desc: "lo-fi early digital drums" },
  { name: "BossDR55", label: "Boss DR55", desc: "primitive minimal analog drums" },
  { name: "BossDR550", label: "Boss DR550", desc: "bright clean digital sampled drums" },
  { name: "CasioRZ1", label: "Casio RZ1", desc: "crunchy lo-fi sampled drums" },
  { name: "CasioSK1", label: "Casio SK1", desc: "toy-grade lo-fi sampler drums" },
  { name: "CasioVL1", label: "Casio VL1", desc: "tiny cheesy calculator drums" },
  { name: "DoepferMS404", label: "Doepfer MS404", desc: "fat analog mono bass synth" },
  { name: "EmuDrumulator", label: "Emu Drumulator", desc: "crunchy classic 8-bit drums" },
  { name: "EmuModular", label: "Emu Modular", desc: "experimental modular synth percussion" },
  { name: "EmuSP12", label: "Emu SP12", desc: "gritty hip-hop sampler drums" },
  { name: "KorgDDM110", label: "Korg DDM110", desc: "punchy digital sampled drums" },
  { name: "KorgKPR77", label: "Korg KPR77", desc: "warm analog drum machine" },
  { name: "KorgKR55", label: "Korg KR55", desc: "smooth vintage analog drums" },
  { name: "KorgKRZ", label: "Korg KRZ", desc: "digital workstation drum sounds" },
  { name: "KorgM1", label: "Korg M1", desc: "iconic 90s house drums" },
  { name: "KorgMinipops", label: "Korg Minipops", desc: "retro bossa preset rhythms" },
  { name: "KorgPoly800", label: "Korg Poly800", desc: "thin analog polysynth percussion" },
  { name: "KorgT3", label: "Korg T3", desc: "bright workstation drum sounds" },
  { name: "Linn9000", label: "Linn 9000", desc: "warm classic sampled drums" },
  { name: "LinnDrum", label: "LinnDrum", desc: "lush 80s pop sampled drums" },
  { name: "LinnLM1", label: "Linn LM1", desc: "legendary early sampled drum machine" },
  { name: "LinnLM2", label: "Linn LM2", desc: "warm classic sampled drums" },
  { name: "MFB512", label: "MFB512", desc: "punchy analog 808-style drums" },
  { name: "MPC1000", label: "Akai MPC1000", desc: "modern clean sampler drums" },
  { name: "MoogConcertMateMG1", label: "Moog Concertmate MG1", desc: "fat warm analog synth" },
  { name: "OberheimDMX", label: "Oberheim DMX", desc: "punchy classic hip-hop drums" },
  { name: "RhodesPolaris", label: "Rhodes Polaris", desc: "warm analog polysynth tones" },
  { name: "RhythmAce", label: "Rhythm Ace", desc: "vintage preset organ rhythms" },
  { name: "RolandCompurhythm1000", label: "Roland CR1000", desc: "clean digital preset rhythms" },
  { name: "RolandCompurhythm78", label: "Roland CR78", desc: "warm vintage preset rhythms" },
  { name: "RolandCompurhythm8000", label: "Roland CR8000", desc: "warm analog preset rhythms" },
  { name: "RolandD110", label: "Roland D110", desc: "digital linear-arithmetic synth tones" },
  { name: "RolandD70", label: "Roland D70", desc: "lush digital workstation tones" },
  { name: "RolandDDR30", label: "Roland DDR30", desc: "punchy digital sampled drums" },
  { name: "RolandJD990", label: "Roland JD990", desc: "rich digital synth tones" },
  { name: "RolandMC202", label: "Roland MC202", desc: "squelchy analog mono synth" },
  { name: "RolandMC303", label: "Roland MC303", desc: "90s groovebox dance drums" },
  { name: "RolandMT32", label: "Roland MT32", desc: "retro digital game-era tones" },
  { name: "RolandR8", label: "Roland R8", desc: "realistic late-80s sampled drums" },
  { name: "RolandS50", label: "Roland S50", desc: "vintage digital sampler tones" },
  { name: "RolandSH09", label: "Roland SH09", desc: "fat analog mono synth" },
  { name: "RolandSystem100", label: "Roland System 100", desc: "classic modular analog synth" },
  { name: "RolandTR505", label: "Roland TR505", desc: "thin clean digital drums" },
  { name: "RolandTR606", label: "Roland TR606", desc: "snappy thin analog drumatix" },
  { name: "RolandTR626", label: "Roland TR626", desc: "bright digital sampled drums" },
  { name: "RolandTR707", label: "Roland TR707", desc: "crisp digital house drums" },
  { name: "RolandTR727", label: "Roland TR727", desc: "digital latin percussion samples" },
  { name: "RolandTR808", label: "Roland TR808", desc: "booming deep hip-hop drums" },
  { name: "RolandTR909", label: "Roland TR909", desc: "punchy analog house techno kit" },
  { name: "SakataDPM48", label: "Sakata DPM48", desc: "rare lo-fi digital drums" },
  { name: "SequentialCircuitsDrumtracks", label: "Sequential Drumtracks", desc: "warm classic sampled drums" },
  { name: "SequentialCircuitsTom", label: "Sequential Tom", desc: "punchy analog tom percussion" },
  { name: "SergeModular", label: "Serge Modular", desc: "experimental west-coast modular synth" },
  { name: "SimmonsSDS400", label: "Simmons SDS400", desc: "electronic pitched analog toms" },
  { name: "SimmonsSDS5", label: "Simmons SDS5", desc: "iconic 80s electronic drums" },
  { name: "SoundmastersR88", label: "Soundmaster R88", desc: "vintage preset organ rhythms" },
  { name: "UnivoxMicroRhythmer12", label: "Univox Micro Rhythmer", desc: "retro preset drum rhythms" },
  { name: "ViscoSpaceDrum", label: "Visco Space Drum", desc: "spacey analog electronic drums" },
  { name: "XdrumLM8953", label: "Xdrum LM8953", desc: "lo-fi sampled drum machine" },
  { name: "YamahaRM50", label: "Yamaha RM50", desc: "realistic digital sampled drums" },
  { name: "YamahaRX21", label: "Yamaha RX21", desc: "dry 80s digital drums" },
  { name: "YamahaRX5", label: "Yamaha RX5", desc: "punchy 80s sampled drums" },
  { name: "YamahaRY30", label: "Yamaha RY30", desc: "clean realistic sampled drums" },
  { name: "YamahaTG33", label: "Yamaha TG33", desc: "vector digital synth tones" },
  { name: "mridangam", label: "Mridangam Bank", desc: "south-indian classical hand drum" },
];

/** Each drum machine voice set (from the tidal-drum-machines manifest) -- NOT every kit has every
 *  voice (e.g. BossDR55 only has bd hh rim sd). The chooser/composer must use a voice the kit really has. */
export const BANK_VOICES: Record<string, string[]> = {
  "AJKPercusyn": ["bd", "cb", "ht", "sd"],
  "AkaiLinn": ["bd", "cb", "cp", "cr", "hh", "ht", "lt", "mt", "oh", "rd", "sd", "sh", "tb"],
  "AkaiMPC60": ["bd", "cp", "cr", "hh", "ht", "lt", "misc", "mt", "oh", "perc", "rd", "rim", "sd"],
  "AkaiXR10": ["bd", "cb", "cp", "cr", "hh", "ht", "lt", "misc", "mt", "oh", "perc", "rd", "rim", "sd", "sh", "tb"],
  "AlesisHR16": ["bd", "cp", "hh", "ht", "lt", "oh", "perc", "rim", "sd", "sh"],
  "AlesisSR16": ["bd", "cb", "cp", "cr", "hh", "misc", "oh", "perc", "rd", "rim", "sd", "sh", "tb"],
  "BossDR110": ["bd", "cp", "cr", "hh", "oh", "rd", "sd"],
  "BossDR220": ["bd", "cp", "cr", "hh", "ht", "lt", "mt", "oh", "perc", "rd", "sd"],
  "BossDR55": ["bd", "hh", "rim", "sd"],
  "BossDR550": ["bd", "cb", "cp", "cr", "hh", "ht", "lt", "misc", "mt", "oh", "perc", "rd", "rim", "sd", "sh", "tb"],
  "CasioRZ1": ["bd", "cb", "cp", "cr", "hh", "ht", "lt", "mt", "rd", "rim", "sd"],
  "CasioSK1": ["bd", "hh", "ht", "mt", "oh", "sd"],
  "CasioVL1": ["bd", "hh", "sd"],
  "DoepferMS404": ["bd", "hh", "lt", "oh", "sd"],
  "EmuDrumulator": ["bd", "cb", "cp", "cr", "hh", "ht", "lt", "mt", "oh", "perc", "rim", "sd"],
  "EmuModular": ["bd", "misc", "perc"],
  "EmuSP12": ["bd", "cb", "cp", "cr", "hh", "ht", "lt", "misc", "mt", "oh", "perc", "rd", "rim", "sd"],
  "KorgDDM110": ["bd", "cp", "cr", "hh", "ht", "lt", "oh", "rim", "sd"],
  "KorgKPR77": ["bd", "cp", "hh", "oh", "sd"],
  "KorgKR55": ["bd", "cb", "cr", "hh", "ht", "oh", "perc", "rim", "sd"],
  "KorgKRZ": ["bd", "cr", "fx", "hh", "ht", "lt", "misc", "oh", "rd", "sd"],
  "KorgM1": ["bd", "cb", "cp", "cr", "hh", "ht", "misc", "mt", "oh", "perc", "rd", "rim", "sd", "sh", "tb"],
  "KorgMinipops": ["bd", "hh", "misc", "oh", "sd"],
  "KorgPoly800": ["bd"],
  "KorgT3": ["bd", "cp", "hh", "misc", "oh", "perc", "rim", "sd", "sh"],
  "Linn9000": ["bd", "cb", "cr", "hh", "ht", "lt", "mt", "oh", "perc", "rd", "rim", "sd", "tb"],
  "LinnDrum": ["bd", "cb", "cp", "cr", "hh", "ht", "lt", "mt", "oh", "perc", "rd", "rim", "sd", "sh", "tb"],
  "LinnLM1": ["bd", "cb", "cp", "hh", "ht", "lt", "oh", "perc", "rim", "sd", "sh", "tb"],
  "LinnLM2": ["bd", "cb", "cp", "cr", "hh", "ht", "lt", "mt", "oh", "rd", "rim", "sd", "sh", "tb"],
  "MFB512": ["bd", "cp", "cr", "hh", "ht", "lt", "mt", "oh", "sd"],
  "MPC1000": ["bd", "cp", "hh", "oh", "perc", "sd", "sh"],
  "MoogConcertMateMG1": ["bd", "sd"],
  "OberheimDMX": ["", "bd", "cp", "cr", "hh", "ht", "lt", "mt", "oh", "rd", "rim", "sd", "sh", "tb"],
  "RhodesPolaris": ["bd", "misc", "sd"],
  "RhythmAce": ["bd", "hh", "ht", "lt", "oh", "perc", "sd"],
  "RolandCompurhythm1000": ["bd", "cb", "cp", "cr", "hh", "ht", "lt", "mt", "oh", "perc", "rd", "rim", "sd"],
  "RolandCompurhythm78": ["bd", "cb", "hh", "misc", "oh", "perc", "sd", "tb"],
  "RolandCompurhythm8000": ["bd", "cb", "cp", "cr", "hh", "ht", "lt", "mt", "oh", "perc", "rim", "sd"],
  "RolandD110": ["bd", "cb", "cr", "hh", "lt", "oh", "perc", "rd", "rim", "sd", "sh", "tb"],
  "RolandD70": ["bd", "cb", "cp", "cr", "hh", "lt", "mt", "oh", "perc", "rd", "rim", "sd", "sh"],
  "RolandDDR30": ["bd", "ht", "lt", "sd"],
  "RolandJD990": ["bd", "cb", "cp", "cr", "hh", "ht", "lt", "misc", "mt", "oh", "perc", "rd", "sd", "tb"],
  "RolandMC202": ["bd", "ht", "perc"],
  "RolandMC303": ["bd", "cb", "cp", "fx", "hh", "ht", "lt", "misc", "mt", "oh", "perc", "rd", "rim", "sd", "sh", "tb"],
  "RolandMT32": ["bd", "cb", "cp", "cr", "hh", "ht", "lt", "mt", "oh", "perc", "rd", "rim", "sd", "sh", "tb"],
  "RolandR8": ["bd", "cb", "cp", "cr", "hh", "ht", "lt", "mt", "oh", "perc", "rd", "rim", "sd", "sh", "tb"],
  "RolandS50": ["bd", "cb", "cp", "cr", "ht", "lt", "misc", "mt", "oh", "perc", "rd", "sd", "sh", "tb"],
  "RolandSH09": ["bd"],
  "RolandSystem100": ["bd", "hh", "misc", "oh", "perc", "sd"],
  "RolandTR505": ["bd", "cb", "cp", "cr", "hh", "ht", "lt", "mt", "oh", "perc", "rd", "rim", "sd"],
  "RolandTR606": ["bd", "cr", "hh", "ht", "lt", "oh", "sd"],
  "RolandTR626": ["bd", "cb", "cp", "cr", "hh", "ht", "lt", "mt", "oh", "perc", "rd", "rim", "sd", "sh", "tb"],
  "RolandTR707": ["bd", "cb", "cp", "cr", "hh", "ht", "lt", "mt", "oh", "rim", "sd", "tb"],
  "RolandTR727": ["perc", "sh"],
  "RolandTR808": ["bd", "cb", "cp", "cr", "hh", "ht", "lt", "mt", "oh", "perc", "rim", "sd", "sh"],
  "RolandTR909": ["bd", "cp", "cr", "hh", "ht", "lt", "mt", "oh", "rd", "rim", "sd"],
  "SakataDPM48": ["bd", "cp", "cr", "hh", "ht", "lt", "mt", "oh", "perc", "rd", "rim", "sd", "sh"],
  "SequentialCircuitsDrumtracks": ["bd", "cb", "cp", "cr", "hh", "ht", "oh", "rd", "rim", "sd", "sh", "tb"],
  "SequentialCircuitsTom": ["bd", "cp", "cr", "hh", "ht", "oh", "sd"],
  "SergeModular": ["bd", "misc", "perc"],
  "SimmonsSDS400": ["ht", "lt", "mt", "sd"],
  "SimmonsSDS5": ["bd", "hh", "ht", "lt", "mt", "oh", "rim", "sd"],
  "SoundmastersR88": ["bd", "cr", "hh", "oh", "sd"],
  "UnivoxMicroRhythmer12": ["bd", "hh", "oh", "sd"],
  "ViscoSpaceDrum": ["bd", "cb", "hh", "ht", "lt", "misc", "mt", "oh", "perc", "rim", "sd"],
  "XdrumLM8953": ["bd", "cr", "hh", "ht", "lt", "mt", "oh", "rd", "rim", "sd", "tb"],
  "YamahaRM50": ["bd", "cb", "cp", "cr", "hh", "ht", "lt", "misc", "mt", "oh", "perc", "rd", "sd", "sh", "tb"],
  "YamahaRX21": ["bd", "cp", "cr", "hh", "ht", "lt", "mt", "oh", "sd"],
  "YamahaRX5": ["bd", "cb", "fx", "hh", "lt", "oh", "rim", "sd", "sh", "tb"],
  "YamahaRY30": ["bd", "cb", "cp", "cr", "hh", "ht", "lt", "misc", "mt", "oh", "perc", "rd", "rim", "sd", "sh", "tb"],
  "YamahaTG33": ["bd", "cb", "cp", "cr", "fx", "ht", "lt", "misc", "mt", "oh", "perc", "rd", "rim", "sd", "sh", "tb"],
};



/** The voices a given drum kit actually has (empty if unknown) — for the composer prompt + validation. */
export function kitVoices(bank: string): string[] {
  return BANK_VOICES[bank] ?? [];
}
