// Stamp the ENGINE ASSET VERSION into the bundle before every build.
// /zaltz (extensionless — the engine, not a file format) + /zaltz.worklet.js are UNHASHED static assets, and the
// serving layer's etag proved unreliable across deploys (a stale etag 304'd
// returning browsers onto WEEKS-old engine builds — every engine-side fix
// silently never reached them). Content-hashed query params make each engine
// release a brand-new URL: no revalidation trap, no edge staleness, ever.
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const h = (p) => createHash("md5").update(readFileSync(join(root, p))).digest("hex").slice(0, 10);
const v = `${h("public/zaltz")}-${h("public/zaltz.worklet.js")}`;
writeFileSync(
  join(root, "lib/engine-version.ts"),
  `// GENERATED by scripts/stamp-engine.mjs at build — do not edit.\nexport const ENGINE_V = "${v}";\n`,
);
console.log("engine assets stamped:", v);
